"""initial full schema

Revision ID: 7c3be29972d5
Revises: 
Create Date: 2026-09-19 01:43:00.558677
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR
from sqlalchemy.dialects import postgresql


revision: str = '7c3be29972d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('leagues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('country_name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('strength_factor', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_code'), 'leagues', ['code'], unique=True)
    op.create_index(op.f('ix_leagues_country_code'), 'leagues', ['country_code'], unique=False)
    op.create_index(op.f('ix_leagues_name'), 'leagues', ['name'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_name'), 'seasons', ['name'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=True),
    sa.Column('attribution_required', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_provider'), 'sources', ['provider'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clubs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('country_name', sa.String(length=120), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_country_code'), 'clubs', ['country_code'], unique=False)
    op.create_index(op.f('ix_clubs_league_id'), 'clubs', ['league_id'], unique=False)
    op.create_index(op.f('ix_clubs_name'), 'clubs', ['name'], unique=False)
    op.create_index(op.f('ix_clubs_slug'), 'clubs', ['slug'], unique=True)
    op.create_table('competitions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('gender', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_league_id'), 'competitions', ['league_id'], unique=False)
    op.create_table('player_comparisons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('player_ids', sa.JSON(), nullable=False),
    sa.Column('custom_weights', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_comparisons_user_id'), 'player_comparisons', ['user_id'], unique=False)
    op.create_table('scouting_missions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('results_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scouting_missions_status'), 'scouting_missions', ['status'], unique=False)
    op.create_index(op.f('ix_scouting_missions_user_id'), 'scouting_missions', ['user_id'], unique=False)
    op.create_table('shortlists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortlists_user_id'), 'shortlists', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mission_plan', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('final_output', sa.JSON(), nullable=True),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('total_llm_calls', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['scouting_missions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_mission_id'), 'agent_runs', ['mission_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nationality_code', sa.String(length=3), nullable=False),
    sa.Column('nationality_name', sa.String(length=120), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('preferred_foot', sa.String(length=10), nullable=True),
    sa.Column('primary_position', sa.String(length=8), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('current_club_id', sa.BigInteger(), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_current_club_id'), 'players', ['current_club_id'], unique=False)
    op.create_index(op.f('ix_players_date_of_birth'), 'players', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_players_full_name'), 'players', ['full_name'], unique=False)
    op.create_index(op.f('ix_players_nationality_code'), 'players', ['nationality_code'], unique=False)
    op.create_index(op.f('ix_players_primary_position'), 'players', ['primary_position'], unique=False)
    op.create_index(op.f('ix_players_slug'), 'players', ['slug'], unique=True)
    op.create_table('agent_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('agent', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_agent'), 'agent_tasks', ['agent'], unique=False)
    op.create_index(op.f('ix_agent_tasks_run_id'), 'agent_tasks', ['run_id'], unique=False)
    op.create_index('ix_at_status', 'agent_tasks', ['status'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('weekly_wages_eur', sa.Integer(), nullable=True),
    sa.Column('clauses', sa.Text(), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_player_id'), 'contracts', ['player_id'], unique=False)
    op.create_table('injuries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=True),
    sa.Column('injury_type', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('days_missed', sa.Integer(), nullable=True),
    sa.Column('matches_missed', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injuries_player_id'), 'injuries', ['player_id'], unique=False)
    op.create_table('market_values',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value_eur', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_values_player_id'), 'market_values', ['player_id'], unique=False)
    op.create_index('ix_mv_lookup', 'market_values', ['player_id', 'date'], unique=False)
    op.create_table('mission_candidates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['scouting_missions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'player_id', name='uq_mission_candidate')
    )
    op.create_index(op.f('ix_mission_candidates_mission_id'), 'mission_candidates', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_candidates_player_id'), 'mission_candidates', ['player_id'], unique=False)
    op.create_table('player_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('embedding', VECTOR(dim=512), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pe_vector', 'player_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_l2_ops'})
    op.create_index(op.f('ix_player_embeddings_player_id'), 'player_embeddings', ['player_id'], unique=False)
    op.create_table('player_match_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('opponent_club_id', sa.BigInteger(), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=False),
    sa.Column('xa', sa.Float(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['opponent_club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', 'competition_id', 'match_date', name='uq_pms_player_match')
    )
    op.create_index(op.f('ix_player_match_stats_club_id'), 'player_match_stats', ['club_id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_competition_id'), 'player_match_stats', ['competition_id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_player_id'), 'player_match_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_season_id'), 'player_match_stats', ['season_id'], unique=False)
    op.create_table('player_positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('share', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_positions_player_id'), 'player_positions', ['player_id'], unique=False)
    op.create_table('player_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_roles_player_id'), 'player_roles', ['player_id'], unique=False)
    op.create_table('player_season_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('appearances', sa.Integer(), nullable=False),
    sa.Column('starts', sa.Integer(), nullable=False),
    sa.Column('subs', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('penalty_goals', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('shots_on_target', sa.Integer(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=False),
    sa.Column('npxg', sa.Float(), nullable=False),
    sa.Column('xa', sa.Float(), nullable=False),
    sa.Column('touches_in_box', sa.Integer(), nullable=False),
    sa.Column('shot_creating_actions', sa.Integer(), nullable=False),
    sa.Column('goal_creating_actions', sa.Integer(), nullable=False),
    sa.Column('passes_attempted', sa.Integer(), nullable=False),
    sa.Column('passes_completed', sa.Integer(), nullable=False),
    sa.Column('progressive_passes', sa.Integer(), nullable=False),
    sa.Column('key_passes', sa.Integer(), nullable=False),
    sa.Column('final_third_passes', sa.Integer(), nullable=False),
    sa.Column('passes_into_box', sa.Integer(), nullable=False),
    sa.Column('through_balls', sa.Integer(), nullable=False),
    sa.Column('long_passes_attempted', sa.Integer(), nullable=False),
    sa.Column('long_passes_completed', sa.Integer(), nullable=False),
    sa.Column('progressive_passing_distance', sa.Integer(), nullable=False),
    sa.Column('carries', sa.Integer(), nullable=False),
    sa.Column('progressive_carries', sa.Integer(), nullable=False),
    sa.Column('carries_into_box', sa.Integer(), nullable=False),
    sa.Column('carries_into_final_third', sa.Integer(), nullable=False),
    sa.Column('carry_distance', sa.Integer(), nullable=False),
    sa.Column('progressive_carry_distance', sa.Integer(), nullable=False),
    sa.Column('successful_dribbles', sa.Integer(), nullable=False),
    sa.Column('dribbles_attempted', sa.Integer(), nullable=False),
    sa.Column('miscontrols', sa.Integer(), nullable=False),
    sa.Column('dispossessions', sa.Integer(), nullable=False),
    sa.Column('touches', sa.Integer(), nullable=False),
    sa.Column('tackles', sa.Integer(), nullable=False),
    sa.Column('interceptions', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('clearances', sa.Integer(), nullable=False),
    sa.Column('defensive_duels_won', sa.Integer(), nullable=False),
    sa.Column('defensive_duels_total', sa.Integer(), nullable=False),
    sa.Column('aerial_duels_won', sa.Integer(), nullable=False),
    sa.Column('aerial_duels_total', sa.Integer(), nullable=False),
    sa.Column('pressures', sa.Integer(), nullable=False),
    sa.Column('pressures_successful', sa.Integer(), nullable=False),
    sa.Column('ball_recoveries', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', 'competition_id', name='uq_pss_player_season_comp')
    )
    op.create_index(op.f('ix_player_season_stats_club_id'), 'player_season_stats', ['club_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_competition_id'), 'player_season_stats', ['competition_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_player_id'), 'player_season_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_position'), 'player_season_stats', ['position'], unique=False)
    op.create_index(op.f('ix_player_season_stats_season_id'), 'player_season_stats', ['season_id'], unique=False)
    op.create_index('ix_pss_value_lookup', 'player_season_stats', ['position', 'minutes_played'], unique=False)
    op.create_table('scouting_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('mission_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('format_type', sa.String(length=10), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['scouting_missions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scouting_reports_player_id'), 'scouting_reports', ['player_id'], unique=False)
    op.create_index(op.f('ix_scouting_reports_user_id'), 'scouting_reports', ['user_id'], unique=False)
    op.create_table('shortlist_players',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shortlist_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['shortlist_id'], ['shortlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortlist_id', 'player_id', name='uq_shortlist_player')
    )
    op.create_index(op.f('ix_shortlist_players_player_id'), 'shortlist_players', ['player_id'], unique=False)
    op.create_index(op.f('ix_shortlist_players_shortlist_id'), 'shortlist_players', ['shortlist_id'], unique=False)
    op.create_index('ix_sp_status', 'shortlist_players', ['status'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('from_club_id', sa.BigInteger(), nullable=True),
    sa.Column('to_club_id', sa.BigInteger(), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('fee_eur', sa.BigInteger(), nullable=True),
    sa.Column('reported_fee', sa.String(length=80), nullable=True),
    sa.Column('is_rumored', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['to_club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_player_id'), 'transfers', ['player_id'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=True),
    sa.Column('tool', sa.String(length=80), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ae_run', 'agent_events', ['run_id', 'seq'], unique=False)
    op.create_index(op.f('ix_agent_events_run_id'), 'agent_events', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_events_run_id'), table_name='agent_events')
    op.drop_index('ix_ae_run', table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_transfers_player_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index('ix_sp_status', table_name='shortlist_players')
    op.drop_index(op.f('ix_shortlist_players_shortlist_id'), table_name='shortlist_players')
    op.drop_index(op.f('ix_shortlist_players_player_id'), table_name='shortlist_players')
    op.drop_table('shortlist_players')
    op.drop_index(op.f('ix_scouting_reports_user_id'), table_name='scouting_reports')
    op.drop_index(op.f('ix_scouting_reports_player_id'), table_name='scouting_reports')
    op.drop_table('scouting_reports')
    op.drop_index('ix_pss_value_lookup', table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_season_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_position'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_player_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_competition_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_club_id'), table_name='player_season_stats')
    op.drop_table('player_season_stats')
    op.drop_index(op.f('ix_player_roles_player_id'), table_name='player_roles')
    op.drop_table('player_roles')
    op.drop_index(op.f('ix_player_positions_player_id'), table_name='player_positions')
    op.drop_table('player_positions')
    op.drop_index(op.f('ix_player_match_stats_season_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_player_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_competition_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_club_id'), table_name='player_match_stats')
    op.drop_table('player_match_stats')
    op.drop_index(op.f('ix_player_embeddings_player_id'), table_name='player_embeddings')
    op.drop_index('ix_pe_vector', table_name='player_embeddings', postgresql_using='hnsw')
    op.drop_table('player_embeddings')
    op.drop_index(op.f('ix_mission_candidates_player_id'), table_name='mission_candidates')
    op.drop_index(op.f('ix_mission_candidates_mission_id'), table_name='mission_candidates')
    op.drop_table('mission_candidates')
    op.drop_index('ix_mv_lookup', table_name='market_values')
    op.drop_index(op.f('ix_market_values_player_id'), table_name='market_values')
    op.drop_table('market_values')
    op.drop_index(op.f('ix_injuries_player_id'), table_name='injuries')
    op.drop_table('injuries')
    op.drop_index(op.f('ix_contracts_player_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_at_status', table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_run_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_agent'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_players_slug'), table_name='players')
    op.drop_index(op.f('ix_players_primary_position'), table_name='players')
    op.drop_index(op.f('ix_players_nationality_code'), table_name='players')
    op.drop_index(op.f('ix_players_full_name'), table_name='players')
    op.drop_index(op.f('ix_players_date_of_birth'), table_name='players')
    op.drop_index(op.f('ix_players_current_club_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_mission_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_shortlists_user_id'), table_name='shortlists')
    op.drop_table('shortlists')
    op.drop_index(op.f('ix_scouting_missions_user_id'), table_name='scouting_missions')
    op.drop_index(op.f('ix_scouting_missions_status'), table_name='scouting_missions')
    op.drop_table('scouting_missions')
    op.drop_index(op.f('ix_player_comparisons_user_id'), table_name='player_comparisons')
    op.drop_table('player_comparisons')
    op.drop_index(op.f('ix_competitions_league_id'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_clubs_slug'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_name'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_league_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_country_code'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sources_provider'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_seasons_name'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_leagues_name'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_country_code'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_code'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###